#!/bin/bash
# Reusable script to install a colorscheme theme into a LazyVim configuration.
#
# Usage:
#   ./setup_theme.sh [OPTIONS]
#
# Options:
#   -c, --config-dir DIR        Neovim config directory (default: ~/.config/lazy-c)
#   -t, --theme REPO            GitHub repo short name, e.g. "folke/tokyonight.nvim" (REQUIRED)
#   -s, --colorscheme NAME      The vim colorscheme name to activate (default: derived from repo)
#   -o, --opts LUA_TABLE        Extra opts as a raw Lua table string, e.g. '{ style = "night" }'
#   -h, --help                  Show this help message
#
# The --theme (-t) parameter accepts the GitHub short name because:
#   • It is exactly what lazy.nvim uses to identify plugins
#   • It uniquely identifies the plugin across all of GitHub
#   • The colorscheme name can usually be inferred from it
#
# Examples:
#   # Tokyo Night with default settings
#   ./setup_theme.sh -c ~/.config/lazy-c -t folke/tokyonight.nvim
#
#   # Tokyo Night "moon" style
#   ./setup_theme.sh -c ~/.config/lazy-c -t folke/tokyonight.nvim -o '{ style = "moon" }'
#
#   # Catppuccin with explicit colorscheme name and flavour
#   ./setup_theme.sh -c ~/.config/lazy-c -t catppuccin/nvim -s catppuccin -o '{ flavour = "mocha" }'
#
#   # Gruvbox
#   ./setup_theme.sh -c ~/.config/lazy-c -t ellisonleao/gruvbox.nvim
#
#   # Rose Pine
#   ./setup_theme.sh -c ~/.config/lazy-c -t rose-pine/neovim -s rose-pine
#
#   # Kanagawa
#   ./setup_theme.sh -c ~/.config/lazy-c -t rebelot/kanagawa.nvim

set -e

# ── Defaults ──────────────────────────────────────────────────────────────────
CONFIG_DIR="$HOME/.config/lazy-c"
THEME=""
COLORSCHEME=""
OPTS=""

# ── Parse arguments ──────────────────────────────────────────────────────────
usage() {
  sed -n '2,/^$/s/^# //p' "$0"
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -c|--config-dir)
      CONFIG_DIR="$2"; shift 2 ;;
    -t|--theme)
      THEME="$2"; shift 2 ;;
    -s|--colorscheme)
      COLORSCHEME="$2"; shift 2 ;;
    -o|--opts)
      OPTS="$2"; shift 2 ;;
    -h|--help)
      usage ;;
    *)
      echo "Unknown option: $1" >&2; usage ;;
  esac
done

# ── Validate required arguments ──────────────────────────────────────────────
if [[ -z "$THEME" ]]; then
  echo "Error: --theme (-t) is required. Provide a GitHub repo, e.g. folke/tokyonight.nvim" >&2
  exit 1
fi

# ── Derive colorscheme name if not provided ──────────────────────────────────
# Strategy: take the repo name, strip common suffixes (.nvim, -nvim, -vim, .vim, -neovim),
# and use what remains as the colorscheme name.
if [[ -z "$COLORSCHEME" ]]; then
  repo_name="${THEME##*/}"                          # e.g. "tokyonight.nvim"
  COLORSCHEME="${repo_name%.nvim}"                  # strip .nvim
  COLORSCHEME="${COLORSCHEME%-nvim}"                # strip -nvim
  COLORSCHEME="${COLORSCHEME%.vim}"                 # strip .vim
  COLORSCHEME="${COLORSCHEME%-vim}"                 # strip -vim
  COLORSCHEME="${COLORSCHEME%-neovim}"              # strip -neovim
  # Handle special case: catppuccin/nvim -> catppuccin (use owner name)
  if [[ "$COLORSCHEME" == "nvim" || "$COLORSCHEME" == "neovim" || "$COLORSCHEME" == "vim" ]]; then
    COLORSCHEME="${THEME%%/*}"
  fi
fi

echo "Theme repo  : $THEME"
echo "Colorscheme : $COLORSCHEME"
echo "Config dir  : $CONFIG_DIR"

# ── Validate config dir ─────────────────────────────────────────────────────
PLUGINS_DIR="$CONFIG_DIR/lua/plugins"
if [[ ! -d "$CONFIG_DIR" ]]; then
  echo "Error: Config directory '$CONFIG_DIR' does not exist." >&2
  echo "Run your LazyVim setup script first." >&2
  exit 1
fi

mkdir -p "$PLUGINS_DIR"

# ── Build the opts block ─────────────────────────────────────────────────────
OPTS_BLOCK=""
if [[ -n "$OPTS" ]]; then
  OPTS_BLOCK="  opts = ${OPTS},"
fi

# ── Write the theme plugin spec ──────────────────────────────────────────────
THEME_FILE="$PLUGINS_DIR/colorscheme.lua"

if [[ -f "$THEME_FILE" ]]; then
  echo "Theme plugin file already exists at $THEME_FILE."
  read -rp "Do you want to replace it? [y/N] " answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    echo "Keeping existing colorscheme.lua. Skipping."
    exit 0
  fi
  echo "Replacing existing colorscheme.lua..."
fi

cat > "$THEME_FILE" <<LUAEOF
-- Colorscheme – auto-generated by setup_theme.sh
-- Theme: ${THEME}
return {
  -- Install the colorscheme plugin
  {
    "${THEME}",
    lazy = false,
    priority = 1000,
${OPTS_BLOCK}
  },

  -- Tell LazyVim to use this colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "${COLORSCHEME}",
    },
  },
}
LUAEOF

echo "✅ Theme '${COLORSCHEME}' (${THEME}) installed to $THEME_FILE"
echo "   Launch Neovim with your config to see it in action."
